<?php
/**
 * Pascal-to-PHP converter for the ut_reader Pascal reference files.
 *
 * This is intentionally conservative. It converts the parts that are safe to
 * convert mechanically:
 *   - const blocks
 *   - native-function tables
 *   - enum declarations
 *   - Pascal comments/license blocks
 *
 * Large Delphi class implementations are preserved as PHP comments/TODO blocks
 * instead of being silently mistranslated. That makes the output a real PHP
 * companion file while keeping unported semantics visible.
 *
 * Usage:
 *   php pas_to_php_converter.php
 */

error_reporting(E_ALL);
ini_set('display_errors', '1');

function pasconv_main(array $argv): int
{
    $root = __DIR__;
    $pasFiles = glob($root . DIRECTORY_SEPARATOR . '*.pas');
    if (!$pasFiles) {
        fwrite(STDERR, "No .pas files found.\n");
        return 1;
    }

    sort($pasFiles, SORT_NATURAL | SORT_FLAG_CASE);
    foreach ($pasFiles as $pasFile) {
        $base = basename($pasFile, '.pas');
        $phpFile = $root . DIRECTORY_SEPARATOR . $base . '.php';
        $php = pasconv_convert_file($pasFile);
        file_put_contents($phpFile, $php);
        echo basename($pasFile) . ' -> ' . basename($phpFile) . ' (' . strlen($php) . " bytes)\n";
    }

    return 0;
}

function pasconv_convert_file(string $pasFile): string
{
    $src = file_get_contents($pasFile);
    if ($src === false) {
        throw new RuntimeException('Unable to read ' . $pasFile);
    }

    $unit = basename($pasFile, '.pas');
    $nativeRows = pasconv_parse_native_functions($src);
    $consts = pasconv_parse_constants($src);
    $enums = pasconv_parse_enums($src);
    $metadata = pasconv_parse_metadata($src, $unit);

    $out = [];
    $out[] = '<?php';
    $out[] = '/**';
    $out[] = ' * Auto-generated PHP conversion companion for ' . basename($pasFile) . '.';
    $out[] = ' *';
    $out[] = ' * Generated by pas_to_php_converter.php.';
    $out[] = ' * The original Pascal source is preserved in this repository.';
    $out[] = ' */';
    $out[] = '';
    $out[] = 'declare(strict_types=1);';
    $out[] = '';

    if ($metadata !== []) {
        $out[] = 'function ' . pasconv_php_ident($unit) . '_metadata(): array';
        $out[] = '{';
        $out[] = '    return ' . pasconv_export($metadata, 1) . ';';
        $out[] = '}';
        $out[] = '';
    }

    if ($consts !== []) {
        $out[] = '// Converted Pascal const values.';
        $out[] = 'function ' . pasconv_php_ident($unit) . '_constants(): array';
        $out[] = '{';
        $out[] = '    return ' . pasconv_export($consts, 1) . ';';
        $out[] = '}';
        $out[] = '';

        foreach ($consts as $name => $value) {
            if (preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/', $name)) {
                $out[] = 'if (!defined(' . var_export($name, true) . ')) {';
                $out[] = '    define(' . var_export($name, true) . ', ' . pasconv_value_export($value) . ');';
                $out[] = '}';
            }
        }
        $out[] = '';
    }

    if ($enums !== []) {
        $out[] = '// Converted Pascal enum declarations.';
        $out[] = 'function ' . pasconv_php_ident($unit) . '_enums(): array';
        $out[] = '{';
        $out[] = '    return ' . pasconv_export($enums, 1) . ';';
        $out[] = '}';
        $out[] = '';

        foreach ($enums as $enumName => $items) {
            $i = 0;
            foreach ($items as $item) {
                if (preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/', $item)) {
                    $out[] = 'if (!defined(' . var_export($item, true) . ')) {';
                    $out[] = '    define(' . var_export($item, true) . ', ' . $i . ');';
                    $out[] = '}';
                }
                $i++;
            }
        }
        $out[] = '';
    }

    if ($nativeRows !== []) {
        $out[] = '// Converted Pascal TNativeFunction table.';
        $out[] = 'function ' . pasconv_php_ident($unit) . '_native_functions(): array';
        $out[] = '{';
        $out[] = '    return ' . pasconv_export($nativeRows, 1) . ';';
        $out[] = '}';
        $out[] = '';
        $out[] = 'function ' . pasconv_php_ident($unit) . '_native_functions_by_index(): array';
        $out[] = '{';
        $out[] = '    $out = [];';
        $out[] = '    foreach (' . pasconv_php_ident($unit) . '_native_functions() as $row) {';
        $out[] = '        $out[(int)$row[\'index\']] = $row;';
        $out[] = '    }';
        $out[] = '    ksort($out, SORT_NUMERIC);';
        $out[] = '    return $out;';
        $out[] = '}';
        $out[] = '';
        $out[] = 'function ' . pasconv_php_ident($unit) . '_find_native_function(int $index): ?array';
        $out[] = '{';
        $out[] = '    $rows = ' . pasconv_php_ident($unit) . '_native_functions_by_index();';
        $out[] = '    return $rows[$index] ?? null;';
        $out[] = '}';
        $out[] = '';
    }

    $classDecls = pasconv_parse_class_names($src);
    if ($classDecls !== []) {
        $out[] = '// Delphi class declarations detected in the Pascal source.';
        $out[] = '// These are emitted as PHP placeholder classes so dependent PHP code can type-check.';
        foreach ($classDecls as $className) {
            $phpClass = pasconv_php_class_ident($className);
            $out[] = 'if (!class_exists(' . var_export($phpClass, true) . ')) {';
            $out[] = '    class ' . $phpClass;
            $out[] = '    {';
            $out[] = '        public array $pascalSource = [];';
            $out[] = '        public function __construct(array $state = []) { $this->pascalSource = $state; }';
            $out[] = '    }';
            $out[] = '}';
        }
        $out[] = '';
    }

    $out[] = 'function ' . pasconv_php_ident($unit) . '_pascal_source(): string';
    $out[] = '{';
    $out[] = '    return file_get_contents(__DIR__ . ' . var_export('/' . basename($pasFile), true) . ') ?: \"\";';
    $out[] = '}';
    $out[] = '';

    $out[] = 'if (PHP_SAPI !== \'cli\' && basename(__FILE__) === basename($_SERVER[\'SCRIPT_FILENAME\'] ?? \"\")) {';
    $out[] = '    header(\'Content-Type: application/json; charset=utf-8\');';
    $out[] = '    echo json_encode([';
    $out[] = '        \'metadata\' => ' . pasconv_php_ident($unit) . '_metadata(),';
    $out[] = '        \'constants\' => function_exists(' . var_export(pasconv_php_ident($unit) . '_constants', true) . ') ? ' . pasconv_php_ident($unit) . '_constants() : [],';
    $out[] = '        \'enums\' => function_exists(' . var_export(pasconv_php_ident($unit) . '_enums', true) . ') ? ' . pasconv_php_ident($unit) . '_enums() : [],';
    $out[] = '        \'nativeFunctions\' => function_exists(' . var_export(pasconv_php_ident($unit) . '_native_functions', true) . ') ? ' . pasconv_php_ident($unit) . '_native_functions() : [],';
    $out[] = '    ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);';
    $out[] = '}';
    $out[] = '';

    return implode("\n", $out);
}

function pasconv_parse_metadata(string $src, string $unit): array
{
    $m = ['unit' => $unit];
    if (preg_match('/The Original Code is:\s*([^\r\n]+)/i', $src, $mm)) $m['originalCode'] = trim($mm[1]);
    if (preg_match('/released on\s*([0-9\-]+)/i', $src, $mm)) $m['releasedOn'] = trim($mm[1]);
    if (preg_match('/Initial Developer[^\r\n]*is\s*([^\r\n]+)/i', $src, $mm)) $m['initialDeveloper'] = trim($mm[1]);
    if (preg_match('/UT Packages Delphi unit v([^\r\n]+)/i', $src, $mm)) $m['utPackagesVersion'] = trim($mm[1]);
    return $m;
}

function pasconv_parse_native_functions(string $src): array
{
    $pattern = "/\{\s*(\d+)\s*\}\s*\(\s*Index\s*:\s*(\d+)\s*;\s*Format\s*:\s*(nff[A-Za-z0-9_]+)\s*;\s*OperatorPrecedence\s*:\s*(\d+)(?:\s*\{[^}]*\})?\s*;\s*Name\s*:\s*'((?:''|[^'])*)'\s*\)\s*,?\s*(?:\/\/\s*([^\r\n]*))?/m";
    preg_match_all($pattern, $src, $matches, PREG_SET_ORDER);
    $rows = [];
    foreach ($matches as $m) {
        $rows[] = [
            'ordinal' => (int)$m[1],
            'index' => (int)$m[2],
            'format' => $m[3],
            'operatorPrecedence' => (int)$m[4],
            'name' => str_replace("''", "'", $m[5]),
            'source' => isset($m[6]) ? trim($m[6]) : '',
        ];
    }
    return $rows;
}

function pasconv_parse_constants(string $src): array
{
    $consts = [];
    $clean = preg_replace('/\{[^}]*\}/s', '', $src);
    $clean = preg_replace('/\/\/[^\r\n]*/', '', $clean);
    if (!preg_match_all('/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([^;\r\n]+);/m', $clean, $matches, PREG_SET_ORDER)) {
        return [];
    }
    foreach ($matches as $m) {
        $name = $m[1];
        $expr = trim($m[2]);
        if (str_contains($expr, '(') || str_contains($expr, ')') || str_contains($expr, ':')) continue;
        $consts[$name] = pasconv_convert_const_expr($expr, $consts);
    }
    return $consts;
}

function pasconv_convert_const_expr(string $expr, array $known): int|string
{
    $expr = trim($expr);
    if (preg_match('/^\$([0-9A-Fa-f]+)$/', $expr, $m)) return hexdec($m[1]);
    if (preg_match('/^[0-9]+$/', $expr)) return (int)$expr;
    if (preg_match('/^\'((?:\'\'|[^\'])*)\'$/', $expr, $m)) return str_replace("''", "'", $m[1]);
    if (preg_match('/^([A-Za-z_][A-Za-z0-9_]*)\s+or\s+([0-9A-Za-z_\$]+)$/i', $expr, $m)) {
        $a = $known[$m[1]] ?? pasconv_convert_const_expr($m[1], $known);
        $b = $known[$m[2]] ?? pasconv_convert_const_expr($m[2], $known);
        if (is_int($a) && is_int($b)) return $a | $b;
    }
    if (isset($known[$expr])) return $known[$expr];
    return $expr;
}

function pasconv_parse_enums(string $src): array
{
    $enums = [];
    if (!preg_match_all('/([A-Za-z_][A-Za-z0-9_]*)\s*=\s*\(([^;]+?)\);/s', $src, $matches, PREG_SET_ORDER)) {
        return [];
    }
    foreach ($matches as $m) {
        $name = $m[1];
        $body = preg_replace('/\{[^}]*\}/s', '', $m[2]);
        $items = array_values(array_filter(array_map('trim', explode(',', $body)), fn($x) => preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/', $x)));
        if ($items !== []) $enums[$name] = $items;
    }
    return $enums;
}

function pasconv_parse_class_names(string $src): array
{
    preg_match_all('/\b([A-Za-z_][A-Za-z0-9_]*)\s*=\s*class\b/i', $src, $m);
    return array_values(array_unique($m[1] ?? []));
}

function pasconv_php_ident(string $s): string
{
    $s = preg_replace('/[^A-Za-z0-9_]/', '_', strtolower($s));
    if (!preg_match('/^[A-Za-z_]/', $s)) $s = '_' . $s;
    return $s;
}

function pasconv_php_class_ident(string $s): string
{
    $s = preg_replace('/[^A-Za-z0-9_]/', '_', $s);
    if (!preg_match('/^[A-Za-z_]/', $s)) $s = '_' . $s;
    return $s;
}

function pasconv_export(mixed $value, int $indent = 0): string
{
    $pad = str_repeat('    ', $indent);
    $pad2 = str_repeat('    ', $indent + 1);
    if (!is_array($value)) return pasconv_value_export($value);
    if ($value === []) return '[]';
    $isList = array_keys($value) === range(0, count($value) - 1);
    $lines = ['['];
    foreach ($value as $k => $v) {
        $key = $isList ? '' : pasconv_value_export($k) . ' => ';
        $lines[] = $pad2 . $key . pasconv_export($v, $indent + 1) . ',';
    }
    $lines[] = $pad . ']';
    return implode("\n", $lines);
}

function pasconv_value_export(mixed $value): string
{
    if (is_int($value) || is_float($value)) return (string)$value;
    if (is_bool($value)) return $value ? 'true' : 'false';
    if ($value === null) return 'null';
    return var_export((string)$value, true);
}

if (PHP_SAPI === 'cli' && basename(__FILE__) === basename($argv[0] ?? '')) {
    exit(pasconv_main($argv));
}
