<?php
/** Catalog file information and dependency diagnostics. */
declare(strict_types=1);
require_once __DIR__.'/lib/CatalogSupport.php';
require_once __DIR__.'/lib/CatalogDependencySchema.php';
require_once __DIR__.'/lib/CatalogCompactDependencies.php';
require_once __DIR__.'/lib/CatalogFileFeedback.php';
require_once __DIR__.'/lib/CatalogDependencyDiagnostics.php';

function file_info_type_from_extension(string $ext):array{$ext=strtolower(trim($ext,'. '));return match($ext){'unr','un2','ut2','ut3','umap'=>['map','type-map'],'umx'=>['music','type-music'],'uax'=>['sound','type-sound'],'utx'=>['texture','type-texture'],'usx'=>['static mesh','type-static-mesh'],'ukx'=>['animation','type-animation'],'upx'=>['particle/effect','type-particle-effect'],'ugx'=>['gui','type-gui'],'con'=>['content','type-content'],'u','upk','uasset'=>['package','type-package'],default=>[$ext!==''?$ext:'unknown','type-unknown']};}
function file_info_source_label(string $source):string{return match($source){'exact_package'=>'exact package','exact_package_alias'=>'exact package alias','exact_object'=>'exact object','exact_object_alias'=>'exact object alias','package_alias'=>'package alias','package_alias_object'=>'alias object','ue_asset_object_path'=>'UE asset path','common_script'=>'common script','asset_registry'=>'asset registry','soft_reference'=>'soft reference','redirector'=>'redirector','none'=>'none',default=>$source!==''?$source:'unknown'};}
function file_info_identity_html(array $dep):string{
    $class=trim((string)($dep['import_class_package']??''));$cn=trim((string)($dep['import_class_name']??''));$class=implode('.',array_filter([$class,$cn],static fn($v)=>$v!==''));
    $html='<strong class="mono path">'.catalog_h((string)($dep['required_object_path']??'')).'</strong>';
    if($class!=='')$html.='<span class="dep-detail">Class: <span class="mono">'.catalog_h($class).'</span></span>';
    $html.='<span class="dep-detail">Import outer index: <span class="mono">'.(int)($dep['import_outer_index']??0).'</span></span>';
    return$html;
}
function file_info_candidate_html(PDO $db,array $dep):string{
    $providerId=(int)($dep['resolved_id']??0);if($providerId<1)return'<span class="muted">No provider package was selected.</span>';
    $provider='<a href="file-info.php?id='.$providerId.'">'.catalog_h((string)($dep['resolved_package']?:$dep['resolved_file'])).'</a>';
    if((string)($dep['status']??'')==='resolved'){
        $ei=$dep['resolved_export_index']!==null?' #'.(int)$dep['resolved_export_index']:'';
        return'<span class="dep-detail"><strong>Provider:</strong> '.$provider.'</span><span class="dep-detail good-text">Object identity matched'.$ei.'.</span>';
    }
    if((string)($dep['status']??'')!=='missing')return'<span class="dep-detail"><strong>Provider:</strong> '.$provider.'</span>';
    $candidates=catalog_dependency_export_candidates($db,$dep);
    $html='<span class="dep-detail"><strong>Provider package found:</strong> '.$provider.'</span>';
    if($candidates===[])return$html.'<span class="dep-detail warning-text"><strong>Candidate export:</strong> no same-name export was found.</span>';
    foreach($candidates as$c){$s=catalog_dependency_candidate_summary($dep,$c);$cls=implode('.',array_filter([(string)$c['class_package'],(string)$c['class_name']],static fn($v)=>trim($v)!==''));$diff=$s['differences']!==[]?implode(', ',$s['differences']):'name/class identity agrees; another VerifyImport condition rejected it';$html.='<div class="dep-candidate"><strong>Candidate export #'.(int)$c['export_index'].'</strong><span class="mono">'.catalog_h((string)$c['object_name']).'</span><span class="dep-detail">Class: <span class="mono">'.catalog_h($cls).'</span></span><span class="dep-detail">Export outer index: <span class="mono">'.(int)$s['actual_outer'].'</span></span><span class="dep-detail">Flags: <span class="mono">'.catalog_h((string)$s['flags_hex']).'</span> · RF_Public: '.($s['public']?'yes':'no').'</span><span class="dep-detail warning-text">Not accepted: '.catalog_h($diff).'.</span></div>';}
    return$html;
}
function file_info_dependency_table(PDO $db,array $dependencies):string{
    if($dependencies===[])return'<p class="muted">No dependencies in this status.</p>';
    $html='<table class="dependency-detail-table" data-sortable-table><thead><tr><th>Status</th><th>Package lookup</th><th>Requested import</th><th>Provider / candidate export</th></tr></thead><tbody>';
    foreach($dependencies as$dep){$status=(string)($dep['status']??'missing');$provider=(int)($dep['resolved_id']??0)>0;$label=$status==='missing'&&$provider?'Object mismatch':ucfirst(str_replace('_',' ',$status));$source=(string)($dep['resolution_source']??'unknown');$confidence=(string)($dep['resolution_confidence']??'unknown');$lookup=$provider?'<strong>Package found</strong>':'<strong>Package not found</strong>';$lookup.='<span class="dep-detail">Method: '.catalog_h(file_info_source_label($source)).'</span><span class="dep-detail">Lookup confidence: '.catalog_h($confidence).'</span>';
        $html.='<tr><td data-sort-value="'.catalog_h($status).'"><span class="dep '.catalog_h($status).'">'.catalog_h($label).'</span></td><td>'.$lookup.'</td><td>'.file_info_identity_html($dep).'</td><td>'.file_info_candidate_html($db,$dep).'</td></tr>';}
    return$html.'</tbody></table>';
}
function file_info_related_files_table(array$rows,string$empty):string{if($rows===[])return'<p class="muted">'.catalog_h($empty).'</p>';$h='<table data-sortable-table><thead><tr><th>Package</th><th>File</th><th>Identity</th><th>Size</th></tr></thead><tbody>';foreach($rows as$r){$fid=(int)($r['id']??0);if($fid<1)continue;$href='file-info.php?id='.$fid;$sort=(string)($r['package_guid']??'').' '.(string)($r['md5']??'').' '.(string)($r['sha1']??'');$h.='<tr><td class="mono"><a href="'.$href.'">'.catalog_h((string)($r['package_name']??'')).'</a></td><td><a href="'.$href.'">'.catalog_h((string)($r['original_name']??'')).'</a></td><td class="mono small used-by-identity" data-sort-value="'.catalog_h($sort).'"><span>GUID: '.catalog_h((string)($r['package_guid']??'')).'</span><span>MD5: '.catalog_h((string)($r['md5']??'')).'</span><span>SHA1: '.catalog_h((string)($r['sha1']??'')).'</span></td><td data-sort-value="'.(int)($r['file_size']??0).'">'.catalog_h(catalog_bytes((int)($r['file_size']??0))).'</td></tr>';}return$h.'</tbody></table>';}

try{
$config=catalog_config();$db=catalog_db($config);catalog_dependency_schema_ensure($db);$id=(int)($_GET['id']??0);$file=catalog_one($db,'SELECT f.*,g.name game_name FROM ue_files f JOIN ue_games g ON g.id=f.game_id WHERE f.id=?',[$id]);if(!$file)throw new RuntimeException('File not found');$deps=catalog_dependency_rows($db,$config,$id);
$dependencyStatuses=['missing'=>'Object missing','package_only'=>'Package only','resolved'=>'Resolved','common'=>'Common'];$groups=array_fill_keys(array_keys($dependencyStatuses),[]);foreach($deps as$d){$s=(string)($d['status']??'');if(isset($groups[$s]))$groups[$s][]=$d;}$requested=strtolower(trim((string)($_GET['dep_status']??'')));$initial=$requested;if($initial!=='all'&&!isset($dependencyStatuses[$initial])){$initial='all';foreach(array_keys($dependencyStatuses)as$s)if($groups[$s]!==[]){$initial=$s;break;}}
catalog_head('File info');echo <<<'CSS'
<style>
.file-info-title{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.file-info-title h1{margin:0}.file-info-context{margin:8px 0}.dependency-tabs{display:flex;flex-wrap:wrap;gap:8px;margin:0 0 12px}.dependency-tab{text-decoration:none}.dependency-tab.is-active{outline:2px solid var(--blue);outline-offset:2px;background:rgba(118,169,255,.13)}.dependency-tab.is-empty{opacity:.62}.dependency-tab-panel[hidden]{display:none}.dependency-status-summary{margin:0 0 10px}.dependency-explainer{padding:12px 14px;margin:0 0 14px;border:1px solid var(--border,#2b3950);border-radius:8px;background:rgba(118,169,255,.06)}.dependency-explainer p{margin:0 0 7px}.dependency-explainer p:last-child{margin-bottom:0}.dependency-detail-table{table-layout:fixed;width:100%}.dependency-detail-table th:nth-child(1){width:12%}.dependency-detail-table th:nth-child(2){width:17%}.dependency-detail-table th:nth-child(3){width:30%}.dependency-detail-table th:nth-child(4){width:41%}.dependency-detail-table td{vertical-align:top;overflow-wrap:anywhere;word-break:break-word}.dep-detail{display:block;margin-top:4px}.dep-candidate{margin-top:8px;padding-top:8px;border-top:1px solid var(--border,#2b3950)}.dep-candidate>span{display:block;margin-top:3px}.warning-text{color:#e8bd55}.good-text{color:#66d9a6}.used-by-identity{min-width:355px}.used-by-identity span{display:block}[data-sortable-table] th{cursor:pointer;user-select:none}[data-sortable-table] th::after{content:'↕';display:inline-block;margin-left:7px;color:var(--muted);font-size:11px;opacity:.7}[data-sortable-table] th.is-sort-ascending::after{content:'▲';color:var(--blue);opacity:1}[data-sortable-table] th.is-sort-descending::after{content:'▼';color:var(--blue);opacity:1}@media(max-width:900px){.dependency-detail-table{table-layout:auto}.dependency-detail-table th{width:auto!important}}
</style>
CSS;
$compressed=(int)($file['is_compressed']??0)===1;[$fileType,$fileTypeClass]=file_info_type_from_extension((string)($file['extension']??''));$packageHref='file-examine.php?id='.$id;$gameHref='game-files.php?id='.(int)$file['game_id'];
echo'<div class="card"><div class="file-info-title"><h1>'.catalog_h($file['package_name']).'</h1><span class="dep file-type-pill '.catalog_h($fileTypeClass).'">'.catalog_h($fileType).'</span></div><p class="file-info-context"><a href="'.$packageHref.'">'.catalog_h($file['original_name']).'</a> / <a href="'.$gameHref.'">'.catalog_h($file['game_name']).'</a></p><p><a class="button" href="download-info.php?id='.$id.'">Download options</a> <a class="button secondary" href="'.$packageHref.'">Examine file</a></p><p><span class="dep '.($compressed?'compressed':'uncompressed').'">'.($compressed?'compressed':'uncompressed').'</span> <span class="mono small">flags 0x'.strtoupper(str_pad(dechex((int)($file['compression_flags']??0)),8,'0',STR_PAD_LEFT)).'</span></p><table><tr><th>MD5</th><td class="mono">'.catalog_h($file['md5']).'</td></tr><tr><th>SHA1</th><td class="mono">'.catalog_h($file['sha1']).'</td></tr><tr><th>GUID</th><td class="mono">'.catalog_h($file['package_guid']).'</td></tr><tr><th>Status</th><td>'.catalog_h($file['scan_status']).'</td></tr><tr><th>Tables</th><td><a href="'.$packageHref.'">'.(int)$file['name_count'].' names / '.(int)$file['import_count'].' imports / '.(int)$file['export_count'].' exports</a></td></tr></table></div>';
echo catalog_file_feedback_form_html($id);$locations=catalog_all($db,'SELECT s.name source_name,s.source_type,l.source_relative_path,l.last_seen_at FROM ue_file_locations l JOIN ue_sources s ON s.id=l.source_id WHERE l.file_id=? AND l.exists_in_source=1 ORDER BY s.name,l.source_relative_path',[$id]);echo'<div class="card"><h2>Source availability</h2>';if(!$locations)echo'<p class="muted">No configured source currently records this file.</p>';else{echo'<p class="muted">Only the source name/type and relative path are shown. Real source base paths are hidden.</p><table data-sortable-table><thead><tr><th>Source</th><th>Type</th><th>Relative path</th><th>Last seen</th></tr></thead><tbody>';foreach($locations as$l)echo'<tr><td>'.catalog_h($l['source_name']).'</td><td class="mono">'.catalog_h($l['source_type']).'</td><td class="mono path">'.catalog_h($l['source_relative_path']).'</td><td>'.catalog_h($l['last_seen_at']).'</td></tr>';echo'</tbody></table>';}echo'</div>';if(!empty($file['scan_notes']))echo'<div class="card"><h2>Scan notes</h2><pre class="mono">'.catalog_h($file['scan_notes']).'</pre></div>';
echo'<div class="card" id="dependencies"><h2>Dependencies</h2>';if(!$deps)echo'<p class="muted">No dependencies were recorded for this package.</p>';else{echo'<div class="dependency-explainer"><p><strong>How to read this:</strong> finding the package is not the same as resolving the object.</p><p><strong>Object mismatch</strong> means UnrealDB found the provider package, but no export satisfied the complete Unreal import identity. The requested serialized import and any same-name export candidates are shown side by side below.</p><p><strong>Resolved</strong> means the object identity was accepted. <strong>Package only</strong> is a package-level dependency without an object match. <strong>Common</strong> is handled as an engine/common dependency. A package lookup labelled “exact package” describes how the provider package was found; it does <em>not</em> mean the object matched.</p></div><nav class="dependency-tabs" role="tablist" data-dependency-default="'.catalog_h($initial).'">';$active=$initial==='all';echo'<a class="dep dependency-tab'.($active?' is-active':'').'" href="#dependency-all" data-dependency-tab="all">All: '.count($deps).'</a>';foreach($dependencyStatuses as$s=>$label){$count=count($groups[$s]);echo'<a class="dep '.$s.' dependency-tab'.($initial===$s?' is-active':'').($count===0?' is-empty':'').'" href="#dependency-'.$s.'" data-dependency-tab="'.$s.'">'.catalog_h($label).': '.$count.'</a>';}echo'</nav><section id="dependency-all" class="dependency-tab-panel" data-dependency-panel="all"'.($initial!=='all'?' hidden':'').'><p class="muted dependency-status-summary">Showing all dependencies: '.count($deps).'.</p>'.file_info_dependency_table($db,$deps).'</section>';foreach($dependencyStatuses as$s=>$label)echo'<section id="dependency-'.$s.'" class="dependency-tab-panel" data-dependency-panel="'.$s.'"'.($initial!==$s?' hidden':'').'><p class="muted dependency-status-summary">Showing '.catalog_h($label).': '.count($groups[$s]).'.</p>'.file_info_dependency_table($db,$groups[$s]).'</section>';}echo'</div>';
$usesById=[];foreach($deps as$d){$target=(int)($d['resolved_id']??0);if($target<1||$target===$id||(string)($d['status']??'')==='common')continue;$usesById[$target]=['id'=>$target,'package_name'=>(string)($d['resolved_package']??''),'original_name'=>(string)($d['resolved_file']??''),'package_guid'=>(string)($d['resolved_guid']??''),'md5'=>(string)($d['resolved_md5']??''),'sha1'=>(string)($d['resolved_sha1']??''),'file_size'=>(int)($d['resolved_size']??0)];}$uses=array_values($usesById);usort($uses,static fn($a,$b)=>strnatcasecmp((string)$a['package_name'],(string)$b['package_name'])?:strnatcasecmp((string)$a['original_name'],(string)$b['original_name']));echo'<div class="card"><h2>Uses ('.count($uses).')</h2>'.file_info_related_files_table($uses,'No resolved dependency files yet.').'</div>';$usedBy=catalog_dependency_used_by_rows($db,$id,200);echo'<div class="card"><h2>Used by ('.count($usedBy).')</h2>'.file_info_related_files_table($usedBy,'No resolved reverse dependency links yet.').'</div>';
echo <<<'HTML'
<script>(function(){'use strict';var tabs=Array.from(document.querySelectorAll('[data-dependency-tab]')),panels=Array.from(document.querySelectorAll('[data-dependency-panel]')),nav=document.querySelector('[data-dependency-default]');function name(){var h=decodeURIComponent(location.hash.replace(/^#/,''));return h.indexOf('dependency-')===0?h.slice(11):(nav?nav.dataset.dependencyDefault:'all')}function activate(n){if(!panels.some(p=>p.dataset.dependencyPanel===n))n=nav?nav.dataset.dependencyDefault:'all';panels.forEach(p=>p.hidden=p.dataset.dependencyPanel!==n);tabs.forEach(t=>t.classList.toggle('is-active',t.dataset.dependencyTab===n))}tabs.forEach(t=>t.addEventListener('click',e=>{e.preventDefault();history.pushState(null,'','#dependency-'+t.dataset.dependencyTab);activate(t.dataset.dependencyTab)}));addEventListener('hashchange',()=>activate(name()));activate(name());document.querySelectorAll('table[data-sortable-table]').forEach(function(table){var head=table.tHead&&table.tHead.rows[0],body=table.tBodies[0];if(!head||!body)return;var active=-1,asc=true;Array.from(head.cells).forEach(function(th,i){th.addEventListener('click',function(){if(active===i)asc=!asc;else{active=i;asc=true}Array.from(body.rows).sort(function(a,b){var x=(a.cells[i]?.dataset.sortValue||a.cells[i]?.textContent||'').trim(),y=(b.cells[i]?.dataset.sortValue||b.cells[i]?.textContent||'').trim();return(asc?1:-1)*x.localeCompare(y,undefined,{numeric:true,sensitivity:'base'})}).forEach(r=>body.appendChild(r))})})})})();</script>
HTML;
catalog_foot();}catch(Throwable$e){catalog_head('Error');echo'<div class="card"><h1>Error</h1><p>'.catalog_h($e->getMessage()).'</p></div>';catalog_foot();}
