<?php
/** Admin view of unresolved dependencies for one game. */
declare(strict_types=1);
require_once __DIR__.'/lib/CatalogSupport.php';
require_once __DIR__.'/lib/BaseGameProtection.php';
require_once __DIR__.'/lib/CatalogDependencyDiagnostics.php';
use UnrealDb\Catalog\Infrastructure\Persistence\PdoGameMissingDependencyQuery;
catalog_start_session();
function game_missing_int(string $key,int $default=0):int{$v=filter_input(INPUT_GET,$key,FILTER_VALIDATE_INT);return$v===false||$v===null?$default:max(0,(int)$v);}
function game_missing_type():string{$v=strtolower(trim((string)($_GET['dependency_type']??'all')));return$v==='base_game'?'base_game':'all';}
function game_missing_url(int $gameId,string $type,array $params=[]):string{$q=array_merge(['game_id'=>$gameId,'dependency_type'=>$type],$params);$q=array_filter($q,static fn(mixed $v):bool=>$v!==null&&$v!==''&&$v!==0);return'game-missing.php?'.http_build_query($q);}
function game_missing_import_class(string $package,string $name):string{return implode('.',array_values(array_filter([$package,$name],static fn(string $v):bool=>trim($v)!=='')));}
try{
$config=catalog_config();$db=catalog_db($config);if(!catalog_require_admin_page('Game Missing Dependencies'))exit;base_game_ensure($db);
$games=catalog_all($db,'SELECT id,name,slug FROM ue_games ORDER BY name');$gameId=game_missing_int('game_id');$game=$gameId>0?catalog_one($db,'SELECT id,name,slug FROM ue_games WHERE id=?',[$gameId]):null;if(!$game)throw new RuntimeException('Choose a valid game from the Games page.');
$type=game_missing_type();$baseGameOnly=$type==='base_game';$selectedPackage=substr(trim((string)($_GET['package']??'')),0,255);if(session_status()===PHP_SESSION_ACTIVE)session_write_close();
$q=new PdoGameMissingDependencyQuery($db);$scope=$baseGameOnly?$q->officialBaseGamePackageNames($gameId):null;$totals=$q->totals($gameId,$scope);$missingObjects=(int)$totals['missing_objects'];$missingPackages=(int)$totals['missing_packages'];$filesWithMissing=(int)$totals['files_with_missing'];$rows=$selectedPackage!==''?$q->detailRows($gameId,$selectedPackage,$scope,500,0):$q->missingRows($gameId,$scope,500,0);$packageRows=$q->packageRows($gameId,$scope,500,0);
foreach($rows as &$row){$path=(string)($row['required_object_path']??'');$parts=explode('.',$path);$row['import_object_name']=(string)(end($parts)?:'');$row['import_class_package']=(string)($row['class_package']??'');$row['import_class_name']=(string)($row['class_name']??'');$row['provider_candidates']=catalog_dependency_provider_candidates($db,$gameId,(int)$row['file_id'],(string)$row['required_package']);foreach($row['provider_candidates'] as &$provider)$provider['candidate_rows']=catalog_dependency_export_candidates($db,$row,(int)$provider['file_id']);unset($provider);}unset($row);
$typeLabel=$baseGameOnly?'Official base-game dependencies only':'All missing dependencies';catalog_head('Missing Dependencies — '.(string)$game['name']);
echo <<<'CSS'
<style>
.game-missing-filter{display:flex;align-items:end;gap:10px;flex-wrap:wrap}.game-missing-filter label{display:grid;gap:5px}.missing-summary{display:grid;grid-template-columns:repeat(3,minmax(180px,1fr));gap:12px;margin:16px 0}.missing-live-filter{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin:0 0 12px}.missing-live-filter input{width:min(520px,100%);min-width:240px}.missing-package-summary{display:flex;gap:8px;flex-wrap:wrap}.missing-package-pill{display:inline-flex;gap:7px;align-items:center;min-width:0;max-width:100%;padding:7px 10px;border:1px solid var(--border,#2b3950);border-radius:8px;overflow-wrap:anywhere}.missing-package-extra{display:none}.missing-package-summary.is-expanded .missing-package-extra,.missing-package-summary.is-filtering .missing-package-extra{display:inline-flex}.missing-package-pill.is-filtered,.missing-detail.is-filtered{display:none!important}.missing-package-more{margin-top:12px}.missing-no-matches{display:none;margin:10px 0 0}.missing-no-matches.is-visible{display:block}.missing-detail{border:1px solid var(--border,#2b3950);border-radius:10px;margin:0 0 12px;overflow:hidden}.missing-detail__title{padding:10px 14px;background:rgba(255,255,255,.035);display:flex;gap:12px;flex-wrap:wrap;align-items:center}.missing-detail__grid{display:grid;grid-template-columns:minmax(190px,.85fr) minmax(260px,1.25fr) minmax(300px,1.6fr)}.missing-detail__cell{padding:12px 14px;min-width:0;overflow-wrap:anywhere}.missing-detail__cell+.missing-detail__cell{border-left:1px solid var(--border,#2b3950)}.missing-label{display:block;font-size:.82em;font-weight:700;margin-bottom:6px}.provider-block+.provider-block{margin-top:12px;padding-top:12px;border-top:1px solid var(--border,#2b3950)}.candidate{margin-top:8px;padding:8px;border:1px solid var(--border,#2b3950);border-radius:7px}.mismatch-reason{margin-top:6px;font-weight:700}.ok-text{font-weight:700}.muted-note{margin-top:5px}@media(max-width:800px){.missing-summary{grid-template-columns:1fr}.missing-detail__grid{grid-template-columns:1fr}.missing-detail__cell+.missing-detail__cell{border-left:0;border-top:1px solid var(--border,#2b3950)}}
</style>
CSS;
echo CatalogUi::pageHeader('Missing Dependencies — '.(string)$game['name'],$typeLabel.'. Package availability and object resolution are separate checks. A package may exist while a requested import still fails VerifyImport.',['Games'=>'games.php','Global Missing Files'=>'missing.php','Game Files'=>'game-files.php?id='.$gameId]);
echo '<section class="ui-section"><div class="ui-section__header"><div><h2>Filter</h2></div></div><div class="ui-section__body"><form class="game-missing-filter" method="get"><label>Game<select name="game_id">';foreach($games as $candidate)echo '<option value="'.(int)$candidate['id'].'"'.((int)$candidate['id']===$gameId?' selected':'').'>'.catalog_h((string)$candidate['name']).'</option>';echo '</select></label><label>Dependency type<select name="dependency_type"><option value="all"'.(!$baseGameOnly?' selected':'').'>All missing dependencies</option><option value="base_game"'.($baseGameOnly?' selected':'').'>Official base-game dependencies only</option></select></label><button type="submit">Apply filters</button></form></div></section>';
echo '<div class="missing-summary">';catalog_stat_card('Missing objects',$missingObjects,'Requested object identities that did not resolve',$missingObjects?'attention':'good');catalog_stat_card('Required packages',$missingPackages,'Logical packages referenced by those imports',$missingPackages?'attention':'good');catalog_stat_card('Affected files',$filesWithMissing,'Files containing unresolved imports',$filesWithMissing?'attention':'good');echo '</div>';
if($packageRows!==[]){$packageTotal=count($packageRows);echo '<section class="ui-section"><div class="ui-section__header"><div><h2>At a glance</h2><p>Unresolved objects grouped by required package. This does not mean the package itself is absent.</p></div></div><div class="ui-section__body"><div class="missing-live-filter"><input type="search" id="missing-package-filter" placeholder="Filter packages…"><span class="muted small" id="missing-package-filter-count"></span></div><div class="missing-package-summary" id="missing-package-summary">';foreach($packageRows as $i=>$p){$name=(string)$p['required_package'];echo '<a class="missing-package-pill'.($i>=10?' missing-package-extra':'').'" data-filter-text="'.catalog_h(strtolower($name)).'" href="'.catalog_h(game_missing_url($gameId,$type,['package'=>$name])).'"><span class="mono">'.catalog_h($name).'</span><strong>'.(int)$p['missing_object_rows'].'</strong><span class="muted small">objects / '.(int)$p['requiring_file_count'].' files</span></a>';}echo '</div><p class="muted missing-no-matches" id="missing-package-no-matches">No packages match this filter.</p>';if($packageTotal>10)echo '<button type="button" class="button secondary missing-package-more" id="missing-package-more">Show '.($packageTotal-10).' more</button>';echo '</div></section>';}
$title=$selectedPackage!==''?'Unresolved objects requiring '.$selectedPackage:'Unresolved object identities';echo '<section class="ui-section"><div class="ui-section__header"><div><h2>'.catalog_h($title).'</h2><p>Each item shows exactly three things: <strong>what the file requested</strong>, <strong>which physical package files are available</strong>, and <strong>what same-name exports those files present</strong>. A package shown here as available is not being reported missing; only the object identity failed.</p></div>';if($selectedPackage!=='')echo '<a class="button secondary" href="'.catalog_h(game_missing_url($gameId,$type)).'">Show all</a>';echo '</div><div class="ui-section__body">';
if($rows===[])echo CatalogUi::emptyState('No unresolved dependency objects','Nothing currently matches the selected scope.');else{echo '<div class="missing-live-filter"><input type="search" id="missing-object-filter" placeholder="Filter files, packages, objects or classes…"><span class="muted small" id="missing-object-filter-count"></span></div><div id="missing-object-list">';foreach($rows as $r){$pkg=(string)$r['required_package'];$class=game_missing_import_class((string)$r['class_package'],(string)$r['class_name']);$providers=(array)($r['provider_candidates']??[]);$filter=strtolower(implode(' ',[(string)$r['owner_package_name'],(string)$r['owner_original_name'],$pkg,(string)$r['required_object_path'],$class]));echo '<article class="missing-detail" data-filter-text="'.catalog_h($filter).'"><div class="missing-detail__title"><strong><a href="file-info.php?id='.(int)$r['file_id'].'">'.catalog_h((string)$r['owner_package_name']).'</a></strong><a class="muted" href="file-examine.php?id='.(int)$r['file_id'].'">'.catalog_h((string)$r['owner_original_name']).'</a></div><div class="missing-detail__grid"><div class="missing-detail__cell"><span class="missing-label">1. FILE REQUESTS</span><div class="mono">'.catalog_h((string)$r['required_object_path']).'</div><div>Class: <span class="mono">'.catalog_h($class!==''?$class:'(not recorded)').'</span></div><div>Package: <strong>'.catalog_h($pkg).'</strong></div></div><div class="missing-detail__cell"><span class="missing-label">2. AVAILABLE PACKAGE FILES</span>';
if($providers===[])echo '<div class="mismatch-reason">No verified physical file providing package '.catalog_h($pkg).' was found.</div>';else{echo '<div class="ok-text">'.count($providers).' verified provider'.(count($providers)===1?'':'s').' found for '.catalog_h($pkg).'.</div>';foreach($providers as $provider){echo '<div class="provider-block"><a href="file-info.php?id='.(int)$provider['file_id'].'"><strong>'.catalog_h((string)$provider['original_name']).'</strong></a><div class="muted small">File #'.(int)$provider['file_id'].' · '.catalog_h((string)$provider['source_kind']).' package provider</div></div>';}}
echo '</div><div class="missing-detail__cell"><span class="missing-label">3. SAME-NAME EXPORTS / RESULT</span>';
if($providers===[])echo '<div>Cannot compare exports because the package file is genuinely unavailable.</div>';else{foreach($providers as $provider){$candidates=(array)($provider['candidate_rows']??[]);echo '<div class="provider-block"><strong>'.catalog_h((string)$provider['original_name']).'</strong>';if($candidates===[]){echo '<div class="mismatch-reason">No export named '.catalog_h((string)$r['import_object_name']).' exists in this provider.</div>';continue;}foreach($candidates as $candidate){$summary=catalog_dependency_candidate_summary($r,$candidate);$diff=(array)$summary['differences'];if(!$summary['public'])$diff[]='export is not RF_Public';$why=$diff!==[]?implode('; ',$diff):'name and class match; VerifyImport still rejected this export, so the remaining mismatch is the outer relationship/parent chain';echo '<div class="candidate"><div><strong>Candidate:</strong> export #'.(int)$candidate['export_index'].' <span class="mono">'.catalog_h((string)$candidate['object_name']).'</span></div><div>Class presented: <span class="mono">'.catalog_h(game_missing_import_class((string)$candidate['class_package'],(string)$candidate['class_name'])).'</span></div><div>Export outer index: '.(int)$candidate['outer_index'].' · Flags: '.catalog_h((string)$summary['flags_hex']).' · RF_Public: '.($summary['public']?'yes':'no').'</div><div class="mismatch-reason">Why it did not resolve: '.catalog_h($why).'</div></div>';}}}echo '</div></div></article>';}echo '</div><p class="muted missing-no-matches" id="missing-object-no-matches">No unresolved objects match this filter.</p>';}
echo '</div></section>';
echo '<script>(function(){function n(v){return(v||"").toLocaleLowerCase().trim()}const pl=document.getElementById("missing-package-summary"),pi=document.getElementById("missing-package-filter"),pb=document.getElementById("missing-package-more"),pc=document.getElementById("missing-package-filter-count"),pe=document.getElementById("missing-package-no-matches");if(pl&&pi){const p=Array.from(pl.querySelectorAll(".missing-package-pill"));function f(){const q=n(pi.value);pl.classList.toggle("is-filtering",q!=="");let m=0;p.forEach(x=>{const h=q===""||n(x.dataset.filterText).includes(q);x.classList.toggle("is-filtered",!h);if(h)m++});if(pc)pc.textContent=q?m+" of "+p.length+" packages":"";if(pe)pe.classList.toggle("is-visible",q&&m===0);if(pb)pb.hidden=q!==""}pi.addEventListener("input",f);if(pb)pb.addEventListener("click",()=>{const e=pl.classList.toggle("is-expanded");pb.textContent=e?"Show less":"Show "+Math.max(0,p.length-10)+" more"})}const ol=document.getElementById("missing-object-list"),oi=document.getElementById("missing-object-filter"),oc=document.getElementById("missing-object-filter-count"),oe=document.getElementById("missing-object-no-matches");if(ol&&oi){const r=Array.from(ol.querySelectorAll(".missing-detail"));oi.addEventListener("input",()=>{const q=n(oi.value);let m=0;r.forEach(x=>{const h=q===""||n(x.dataset.filterText).includes(q);x.classList.toggle("is-filtered",!h);if(h)m++});if(oc)oc.textContent=q?m+" of "+r.length+" objects":"";if(oe)oe.classList.toggle("is-visible",q&&m===0)})}})();</script>';catalog_foot();
}catch(Throwable $error){if(!headers_sent())catalog_head('Game missing dependencies error');echo CatalogUi::alert('danger',$error->getMessage(),'The filtered missing-dependency page could not be loaded.');catalog_foot();}
