<?php
/**
 * Minimal bootstrap for machine health/readiness probes.
 *
 * Deliberately excludes the full page-support bootstrap so probes do not
 * traverse HTML transforms, public response caching, crawler/burst middleware,
 * authentication helpers or request resource tracing. The normal web/API
 * bootstrap remains unchanged.
 */
declare(strict_types=1);

// Health/readiness traffic is generated by infrastructure. Do not let frequent
// probes randomly persist request-performance samples back into MySQL.
$GLOBALS['catalog_performance_persist_disabled'] = true;

require_once dirname(__DIR__) . '/lib/CatalogSupportCore.php';
require_once __DIR__ . '/autoload.php';

use UnrealDb\Catalog\Presentation\Http\CatalogApplication;

function catalog_operational_application(): CatalogApplication
{
    return CatalogApplication::boot(false);
}
