<?php
/** Indexed read model for the per-game missing-dependency page. */
declare(strict_types=1);
namespace UnrealDb\Catalog\Infrastructure\Persistence;
use PDO;
final class PdoGameMissingDependencyQuery
{
    public function __construct(private readonly PDO $db) {}
    public function officialBaseGamePackageNames(int $gameId): array
    {
        if($gameId<1)return[];$s=$this->db->prepare('SELECT b.package_name,b.original_name,f.package_name source_package_name,f.original_name source_original_name FROM ue_base_game_files b LEFT JOIN ue_files f ON f.id=b.source_file_id AND f.game_id=b.game_id WHERE b.game_id=?');$s->execute([$gameId]);$names=[];
        while(($r=$s->fetch(PDO::FETCH_ASSOC))!==false)foreach([(string)($r['package_name']??''),self::filenameStem((string)($r['original_name']??'')),(string)($r['source_package_name']??''),self::filenameStem((string)($r['source_original_name']??''))] as $n){$n=trim($n);if($n==='')continue;$k=function_exists('mb_strtolower')?mb_strtolower($n,'UTF-8'):strtolower($n);$names[$k]??=$n;}natcasesort($names);return array_values($names);
    }
    /** @return array{stale_files:int,stale_rows:int,stale_missing_rows:int,owners:list<array<string,mixed>>} */
    public function projectionHealth(int $gameId,int $limit=20):array
    {
        $limit=max(1,min(100,$limit));
        if($gameId<1)return['stale_files'=>0,'stale_rows'=>0,'stale_missing_rows'=>0,'owners'=>[]];
        $predicate='(f.id IS NULL OR f.scan_status<>"verified")';
        $q=$this->db->prepare('SELECT COUNT(DISTINCT s.file_id) stale_files,COUNT(*) stale_rows,COALESCE(SUM(s.missing_count),0) stale_missing_rows FROM ue_dependency_package_summaries s LEFT JOIN ue_files f ON f.id=s.file_id AND f.game_id=s.game_id WHERE s.game_id=? AND '.$predicate);
        $q->execute([$gameId]);$r=$q->fetch(PDO::FETCH_ASSOC)?:[];
        $owners=$this->db->prepare('SELECT s.file_id,COALESCE(f.scan_status,"missing") scan_status,COUNT(*) summary_rows,COALESCE(SUM(s.missing_count),0) stale_missing_rows,(SELECT COUNT(*) FROM ue_dependency_links l WHERE l.file_id=s.file_id) live_dependency_rows FROM ue_dependency_package_summaries s LEFT JOIN ue_files f ON f.id=s.file_id AND f.game_id=s.game_id WHERE s.game_id=? AND '.$predicate.' GROUP BY s.file_id,f.scan_status ORDER BY stale_missing_rows DESC,summary_rows DESC,s.file_id LIMIT '.$limit);
        $owners->execute([$gameId]);
        return['stale_files'=>(int)($r['stale_files']??0),'stale_rows'=>(int)($r['stale_rows']??0),'stale_missing_rows'=>(int)($r['stale_missing_rows']??0),'owners'=>$owners->fetchAll(PDO::FETCH_ASSOC)?:[]];
    }
    public function totals(int $gameId,?array $packageNames):array{if($gameId<1||$packageNames===[])return['missing_objects'=>0,'missing_packages'=>0,'files_with_missing'=>0];$this->requireSummaryProjection();[$w,$a]=$this->summaryWhere('s',$gameId,$packageNames);$s=$this->db->prepare('SELECT COALESCE(SUM(s.missing_count),0) missing_objects,COUNT(DISTINCT s.required_package) missing_packages,COUNT(DISTINCT s.file_id) files_with_missing FROM ue_dependency_package_summaries s WHERE '.$w);$s->execute($a);$r=$s->fetch(PDO::FETCH_ASSOC)?:[];return['missing_objects'=>(int)($r['missing_objects']??0),'missing_packages'=>(int)($r['missing_packages']??0),'files_with_missing'=>(int)($r['files_with_missing']??0)];}
    public function fileRows(int $gameId,?array $packageNames,int $limit,int $offset):array{$limit=max(1,min(500,$limit));$offset=max(0,$offset);if($gameId<1||$packageNames===[])return[];$this->requireSummaryProjection();[$w,$a]=$this->summaryWhere('s',$gameId,$packageNames);$s=$this->db->prepare('SELECT f.id file_id,f.package_name,f.original_name,g.name game_name,SUM(s.missing_count) missing_object_rows,COUNT(*) missing_package_count,GROUP_CONCAT(s.required_package ORDER BY s.required_package SEPARATOR ", ") missing_package_names FROM ue_dependency_package_summaries s JOIN ue_files f ON f.id=s.file_id JOIN ue_games g ON g.id=s.game_id WHERE '.$w.' GROUP BY f.id,f.package_name,f.original_name,g.name ORDER BY missing_object_rows DESC,missing_package_count DESC,f.id LIMIT '.$limit.' OFFSET '.$offset);$s->execute($a);return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
    public function packageRows(int $gameId,?array $packageNames,int $limit,int $offset,string $search=''):array{$limit=max(1,min(500,$limit));$offset=max(0,$offset);if($gameId<1||$packageNames===[])return[];$this->requireSummaryProjection();[$w,$a]=$this->summaryWhere('s',$gameId,$packageNames);$search=trim($search);if($search!==''){$w.=' AND s.required_package LIKE ?';$a[]='%'.$search.'%';}$s=$this->db->prepare('SELECT s.required_package,SUM(s.missing_count) missing_object_rows,COUNT(DISTINCT s.file_id) requiring_file_count FROM ue_dependency_package_summaries s WHERE '.$w.' GROUP BY s.required_package ORDER BY missing_object_rows DESC,requiring_file_count DESC,s.required_package LIMIT '.$limit.' OFFSET '.$offset);$s->execute($a);return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
    public function objectTotal(int $gameId,string $packageName,?array $packageNames,string $search=''):int{$packageName=trim($packageName);if($gameId<1||$packageName===''||!$this->scopeContains($packageName,$packageNames))return 0;$termId=$this->termId($packageName);if($termId<1)return 0;$w='f.game_id=? AND f.scan_status="verified" AND l.status=0 AND l.required_package_term_id=?';$a=[$gameId,$termId];$search=trim($search);if($search!==''){$w.=' AND CONVERT(object_term.value_prefix USING utf8mb4) LIKE ?';$a[]='%'.$search.'%';}$q=$this->db->prepare('SELECT COUNT(DISTINCT l.required_object_term_id) FROM ue_dependency_links l JOIN ue_files f ON f.id=l.file_id JOIN ue_terms object_term ON object_term.id=l.required_object_term_id WHERE '.$w);$q->execute($a);return(int)($q->fetchColumn()?:0);}
    public function objectRows(int $gameId,string $packageName,?array $packageNames,int $limit,int $offset,string $search=''):array{$limit=max(1,min(500,$limit));$offset=max(0,$offset);$packageName=trim($packageName);if($gameId<1||$packageName===''||!$this->scopeContains($packageName,$packageNames))return[];$termId=$this->termId($packageName);if($termId<1)return[];$w='f.game_id=? AND f.scan_status="verified" AND l.status=0 AND l.required_package_term_id=?';$a=[$gameId,$termId];$search=trim($search);if($search!==''){$w.=' AND CONVERT(object_term.value_prefix USING utf8mb4) LIKE ?';$a[]='%'.$search.'%';}$s=$this->db->prepare('SELECT l.required_object_term_id,MAX(CONVERT(object_term.value_prefix USING utf8mb4)) required_object_path,COUNT(*) missing_import_count,COUNT(DISTINCT l.file_id) affected_file_count FROM ue_dependency_links l JOIN ue_files f ON f.id=l.file_id JOIN ue_terms object_term ON object_term.id=l.required_object_term_id WHERE '.$w.' GROUP BY l.required_object_term_id ORDER BY missing_import_count DESC,affected_file_count DESC,required_object_path LIMIT '.$limit.' OFFSET '.$offset);$s->execute($a);return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
    public function objectFileRows(int $gameId,string $packageName,string $objectPath,?array $packageNames,int $limit,int $offset):array{$limit=max(1,min(500,$limit));$offset=max(0,$offset);$packageName=trim($packageName);$objectPath=trim($objectPath);if($gameId<1||$packageName===''||$objectPath===''||!$this->scopeContains($packageName,$packageNames))return[];$packageTermId=$this->termId($packageName);$objectTermId=$this->termId($objectPath);if($packageTermId<1||$objectTermId<1)return[];$s=$this->db->prepare($this->missingSelect().' WHERE f.game_id=? AND f.scan_status="verified" AND l.status=0 AND l.required_package_term_id=? AND l.required_object_term_id=? ORDER BY f.package_name,f.original_name,l.import_index LIMIT '.$limit.' OFFSET '.$offset);$s->execute([$gameId,$packageTermId,$objectTermId]);return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
    public function missingRows(int $gameId,?array $packageNames,int $limit,int $offset):array{$limit=max(1,min(500,$limit));$offset=max(0,$offset);if($gameId<1||$packageNames===[])return[];$termIds=$packageNames===null?null:$this->termIds($packageNames);[$w,$a]=$this->linkWhere($gameId,$termIds);$s=$this->db->prepare($this->missingSelect().' WHERE '.$w.' ORDER BY f.package_name,required_package,required_object_path,l.import_index LIMIT '.$limit.' OFFSET '.$offset);$s->execute($a);return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
    public function detailTotal(int $gameId,string $packageName,?array $packageNames):int{$packageName=trim($packageName);if($gameId<1||$packageName===''||!$this->scopeContains($packageName,$packageNames))return 0;$this->requireSummaryProjection();$s=$this->db->prepare('SELECT COALESCE(SUM(missing_count),0) FROM ue_dependency_package_summaries WHERE game_id=? AND missing_count>0 AND required_package=?');$s->execute([$gameId,$packageName]);return(int)($s->fetchColumn()?:0);}
    public function detailRows(int $gameId,string $packageName,?array $packageNames,int $limit,int $offset):array{$limit=max(1,min(500,$limit));$offset=max(0,$offset);$packageName=trim($packageName);if($gameId<1||$packageName===''||!$this->scopeContains($packageName,$packageNames))return[];$termId=$this->termId($packageName);if($termId<1)return[];$s=$this->db->prepare($this->missingSelect().' WHERE f.game_id=? AND f.scan_status="verified" AND l.status=0 AND l.required_package_term_id=? ORDER BY f.id,l.import_index LIMIT '.$limit.' OFFSET '.$offset);$s->execute([$gameId,$termId]);return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
    private function missingSelect():string{return 'SELECT f.id file_id,f.package_name owner_package_name,f.original_name owner_original_name,CONVERT(package_term.value_prefix USING utf8mb4) required_package,CONVERT(object_term.value_prefix USING utf8mb4) required_object_path,COALESCE(CONVERT(class_package_term.value_prefix USING utf8mb4),"") class_package,COALESCE(CONVERT(class_name_term.value_prefix USING utf8mb4),"") class_name,l.import_index,l.resolved_file_id,rf.package_name provider_package_name,rf.original_name provider_original_name FROM ue_dependency_links l JOIN ue_files f ON f.id=l.file_id JOIN ue_terms package_term ON package_term.id=l.required_package_term_id JOIN ue_terms object_term ON object_term.id=l.required_object_term_id LEFT JOIN ue_terms class_package_term ON class_package_term.id=l.import_class_package_term_id LEFT JOIN ue_terms class_name_term ON class_name_term.id=l.import_class_name_term_id LEFT JOIN ue_files rf ON rf.id=l.resolved_file_id';}
    private function requireSummaryProjection():void{if(!(new PdoDependencyPackageSummary($this->db))->available())throw new \RuntimeException('Current dependency package summary projection is unavailable; rebuild it before viewing missing dependencies.');}
    private function summaryWhere(string $alias,int $gameId,?array $packageNames):array{$w=$alias.'.game_id=? AND '.$alias.'.missing_count>0 AND EXISTS (SELECT 1 FROM ue_files summary_owner WHERE summary_owner.id='.$alias.'.file_id AND summary_owner.game_id='.$alias.'.game_id AND summary_owner.scan_status="verified")';$a=[$gameId];if($packageNames!==null){if($packageNames===[])return['1=0',[]];$w.=' AND '.$alias.'.required_package IN ('.implode(',',array_fill(0,count($packageNames),'?')).')';array_push($a,...$packageNames);}return[$w,$a];}
    private function linkWhere(int $gameId,?array $termIds):array{$w='f.game_id=? AND f.scan_status="verified" AND l.status=0';$a=[$gameId];if($termIds!==null){if($termIds===[])return['1=0',[]];$w.=' AND l.required_package_term_id IN ('.implode(',',array_fill(0,count($termIds),'?')).')';array_push($a,...$termIds);}return[$w,$a];}
    private function scopeContains(string $packageName,?array $packageNames):bool{if($packageNames===null)return true;$needle=function_exists('mb_strtolower')?mb_strtolower(trim($packageName),'UTF-8'):strtolower(trim($packageName));foreach($packageNames as $c){$c=function_exists('mb_strtolower')?mb_strtolower(trim((string)$c),'UTF-8'):strtolower(trim((string)$c));if($c!==''&&hash_equals($c,$needle))return true;}return false;}
    private function termIds(array $values):array{$ids=[];foreach($values as $v){$id=$this->termId((string)$v);if($id>0)$ids[$id]=true;}return array_map('intval',array_keys($ids));}
    private function termId(string $value):int{$value=trim($value);if($value==='')return 0;$s=$this->db->prepare('SELECT id,value_prefix FROM ue_terms WHERE value_hash=? AND value_length=? LIMIT 1');$s->execute([md5($value,true),strlen($value)]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!is_array($r))return 0;$stored=(string)($r['value_prefix']??'');if(!hash_equals($stored,$value)&&!hash_equals($stored,substr($value,0,200)))return 0;return max(0,(int)$r['id']);}
    private static function filenameStem(string $filename):string{$filename=trim(str_replace('\\','/',$filename));$slash=strrpos($filename,'/');if($slash!==false)$filename=substr($filename,$slash+1);$dot=strrpos($filename,'.');return$dot!==false?substr($filename,0,$dot):$filename;}
}
